CREATE TABLE IF NOT EXISTS `anime` (
  `id` int(10) unsigned AUTO_INCREMENT NOT NULL,
  `jpName` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL,
  `enName` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `frName` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `synopsis` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `type` int(10),
  `episodes` int(10),
  `status` int(10),
  `premiered` int(10),
  `startAiring` date,
  `endAiring` date,
  `broadcast` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `producer` int(10),
  `licensor` int(10),
  `studio` int(10),
  `source` int(10),
  `duration` int(10),
  `rating` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci,
  `score` float(10),
  `ranked` int(10),
  `popularity` int(10),
  `members` int(10),
  `favorites` int(10),
  PRIMARY KEY (`id`),
) ENGINE=InnoDB AUTO_INCREMENT=22 DEFAULT CHARSET=utf8;